fix typo

diff --git a/bundle b/bundle
--- a/bundle
+++ b/bundle
@@ -178,7 +178,7 @@ recursion () {
     if cd ..; then
         true
     else
-        echo "Unnable to 'cd ..', Why" >&2
+        echo "Unable to 'cd ..', Why" >&2
         exit 1
     fi
 }
